/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Zeynep
 */
public class Anasayfa extends javax.swing.JFrame {

    /**
     * Creates new form Anasayfa
     */
    public Anasayfa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        anasayfapdbtn = new javax.swing.JButton();
        anasayfakdbtn = new javax.swing.JButton();
        anasayfacpbtn = new javax.swing.JButton();
        anasayfacnrbtn = new javax.swing.JButton();
        anasayfaornbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));

        anasayfapdbtn.setText("Personel Information");
        anasayfapdbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anasayfapdbtnActionPerformed(evt);
            }
        });

        anasayfakdbtn.setText("Customer Information");
        anasayfakdbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anasayfakdbtnActionPerformed(evt);
            }
        });

        anasayfacpbtn.setText("Change Password");

        anasayfacnrbtn.setText("Create a new Report");
        anasayfacnrbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anasayfacnrbtnActionPerformed(evt);
            }
        });

        anasayfaornbtn.setText("Open with Report No");
        anasayfaornbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anasayfaornbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(anasayfapdbtn)
                        .addGap(31, 31, 31)
                        .addComponent(anasayfakdbtn)
                        .addGap(32, 32, 32)
                        .addComponent(anasayfacpbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(anasayfacnrbtn)
                        .addGap(36, 36, 36)
                        .addComponent(anasayfaornbtn)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anasayfapdbtn)
                    .addComponent(anasayfakdbtn)
                    .addComponent(anasayfacpbtn))
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anasayfacnrbtn)
                    .addComponent(anasayfaornbtn))
                .addContainerGap(206, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anasayfapdbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anasayfapdbtnActionPerformed
        PersonelInformation pinf= new PersonelInformation();
        pinf.setVisible(true);
        
        
    }//GEN-LAST:event_anasayfapdbtnActionPerformed

    private void anasayfakdbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anasayfakdbtnActionPerformed
       
        CustomerInformation cinf=new CustomerInformation();
        cinf.setVisible(true);
        
    }//GEN-LAST:event_anasayfakdbtnActionPerformed

    private void anasayfacnrbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anasayfacnrbtnActionPerformed
       Rapor r=new Rapor();
       r.setVisible(true);
        
    }//GEN-LAST:event_anasayfacnrbtnActionPerformed

    private void anasayfaornbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anasayfaornbtnActionPerformed
       OpenwithNo own=new OpenwithNo();
       own.setVisible(true);
    }//GEN-LAST:event_anasayfaornbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Anasayfa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anasayfacnrbtn;
    private javax.swing.JButton anasayfacpbtn;
    private javax.swing.JButton anasayfakdbtn;
    private javax.swing.JButton anasayfaornbtn;
    private javax.swing.JButton anasayfapdbtn;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
